apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project

spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone-project
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: udacity-capstone-project
    spec:
      containers:
        - name: udacity-capstone-project
          image: 133860621760.dkr.ecr.us-west-2.amazonaws.com/udacity-capstone-project:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"


apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-project

spec:
  selector:
    app: udacity-capstone-project
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer


