apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-project

spec:
  selector:
    app: udacity-capstone-project
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-capstone-project
  template:
    metadata:
      labels:
        app: udacity-capstone-project
    spec:
      containers:
        - name: udacity-capstone-project
          image: 133860621760.dkr.ecr.us-west-2.amazonaws.com/udacity-capstone-project:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"