Description: >
    Jenkins Instances CloudFormation Deployment.
    This template deploys two Security Groups and two EC2 instances 
    (One for Jenkins Master and one for Jenkins Agent)

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  ImageId:
    Description: ImageId for Jenkins instances
    Type: String
  MyIP:
    Description: My IP address for SSH access in Jenkins instances.
    Type: String
Resources:
  RoleforECRAccess:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
  
  ServerInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref RoleforECRAccess
      Path: /
  
  JenkinsMasterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access on ports 22 and 8080
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPC"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref MyIP
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
        
  JenkinsAgentSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access from MyIP and JenkinsMaster
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPC"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: !Ref MyIP
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
        
  SGIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      GroupId: !Ref JenkinsAgentSecurityGroup
      SourceSecurityGroupId: !GetAtt JenkinsMasterSecurityGroup.GroupId

  JenkinsMasterInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t3.medium
      KeyName: jenkinsmaster
      NetworkInterfaces: 
      - AssociatePublicIpAddress: true
        DeviceIndex: "0"
        GroupSet: 
          - Ref: "JenkinsMasterSecurityGroup"
        SubnetId: 
          Fn::ImportValue:
            !Sub "${EnvironmentName}-PublicSubnet1"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: 20
      UserData:
          Fn::Base64: |
            #! /usr/bin/bash
            
            # Install Java
            apt update -y
            apt install default-jre -y
            apt install default-jdk -y
            
            # Install Jenkins 
            wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
            sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
            apt update -y
            apt install jenkins -y
            
            # Start Jenkins
            systemctl start jenkins
            
            # Opening the firewall
            ufw allow OpenSSH
            ufw enable
            ufw allow 8080

      Tags:
        -
         Key: Name
         Value: Jenkins Master



  JenkinsAgentInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t3.medium
      KeyName: jenkinsagent
      IamInstanceProfile: !Ref ServerInstanceProfile
      NetworkInterfaces: 
      - AssociatePublicIpAddress: true
        DeviceIndex: "0"
        GroupSet: 
          - Ref: "JenkinsAgentSecurityGroup"
        SubnetId: 
          Fn::ImportValue:
            !Sub "${EnvironmentName}-PublicSubnet1"
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: 20
      UserData:
          Fn::Base64: |
            #! /usr/bin/bash
            
            # Install Java
            apt update -y
            apt install default-jre -y
            apt install default-jdk -y
            
            # Install NodeJS and npm
            apt update -y
            apt install nodejs -y
            apt install npm -y
            
            # Install Hadolint 
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            
            # Install Docker 
            apt install apt-transport-https ca-certificates curl software-properties-common -y
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            apt update -y
            apt install docker-ce -y
            
            # Executing Docker without sudo
            usermod -aG docker ubuntu

            # Install AWS CLI
            apt install -y unzip 
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
            
            # Install Kubectl
            apt update -y
            apt install -y apt-transport-https ca-certificates curl
            curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
            echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list
            apt update -y
            apt install -y kubectl
            
            # Install jq
            apt install jq -y

      Tags:
        -
         Key: Name
         Value: Jenkins Agent
