version: 2.1
jobs:
    lint-application:
        docker:
          - image: circleci/node:13.8.0
        steps:
          - checkout
          - restore_cache:
              keys: [lint-app]
          - run: 
              name: Install packages
              command: |
                npm install
                
                #Install Hadolint
                wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
          - save_cache:
              paths: [node_modules]
              key: lint-app
          - run:
              name: Lint Application
              command: |
                npm run lint
          - run:
              name: Lint Docker File
              command: |
                hadolint Dockerfile
    
    test-application:
        docker:
           - image: circleci/node:13.8.0
        steps:
           - checkout
           - restore_cache:
              keys: [test-application]
           - run:
              name: Install packages
              command: |
                npm install
           - save_cache:
              paths: [node_modules]
              key: test-application
           - run:
              name: Application Test
              command: |
                 npm run test
                 
workflows:
  default:
    jobs:
      - lint-application
      - test-application:
          requires: [lint-application]
